### ISSUE TITLE
Add U2F support

### ISSUE THREAD

**Issue by mxmauro** [algorand/ledger-app-algorand#1]
Hi,

To allow people to use web-based wallets with hardware devices, there are two communications methods: WebUSB and U2F.

Currently, the former has many limitations:

1. It only works on Chrome
2. It only works on Mac and Linux if the user has advanced knowledge on OS management.

The current code does not support U2F which is the method used by well-known wallets like MyCryptoWallet, MyEtherWallet, etc.

If I'm right, the change only involves adding the following definitions to the makefile file:

```# U2F
DEFINES   += HAVE_U2F HAVE_IO_U2F
DEFINES   += U2F_PROXY_MAGIC=\"algo\"
DEFINES   += USB_SEGMENT_SIZE=64
DEFINES   += BLE_SEGMENT_SIZE=32 #max MTU, min 20```

`U2F_PROXY_MAGIC` is the custom scramble key used later with ledger code.

Regards,
Mauro.

**Comment by zeldovich** [comment]
What's your sense on where the U2F tunneling support is headed?

This blog post from Ledger seems to suggest that they see WebUSB as the way forward: https://www.ledger.com/windows-10-update-sunsetting-u2f-tunnel-transport-for-ledger-devices/

**Comment by mxmauro** [comment]
It is supposed to be the future but the reality is, on Windows 10, it is installed as two devices: One a HID-compliant fido and the other, an unknown device identified as Nano S

The fido device is used by Ledger Live but Chrome does not identify it. Also if you try to use the device in some VM with Linux, a workaround is to force it to act like a Microsoft WinUSB device.

On the other hand U2F is supported by more browsers,

**Comment by zeldovich** [comment]
Hmm, yeah, messy situation indeed.

Do you have an app that you're developing where you want to use U2F to talk to the Algorand app on the Ledger, that I might use as an example to test out Ledger's U2F tunneling support?

**Comment by mxmauro** [comment]
The goal is to use it in a web-based wallet for users. (May be other companies like MyCrypto want to add support in some future).

My current code only works with WebUSB on Linux/Mac and Chrome although it has some drawbacks (I must serialize messages else the device hangs).

We would like to support also U2F as a fallback communication method if WebUSB is not available.

I can open the device thru U2F but I'm unable to send anything because the firmware does not recognize the data. As far as I saw, It adds some headers and xor's it with the scramble key.

I can create a little library (currently I'm working on a mini react app to show if all works) and share with you.

**Comment by zeldovich** [comment]
Sounds good; if you can cook up a little test app that I can use to test the U2F support, I'll try to add U2F support to the Algorand app.  Thanks!

**Comment by mxmauro** [comment]
Excellent. I'll contact you again next week.

**Comment by mxmauro** [comment]
Hi @zeldovich 

[Here](https://github.com/randlabs/Ledger_App_Demo) I uploaded a little React App with a sample code to get the address stored in Ledger.

Some notes:

1. Set `HTTPS` environment variable to `true` before launching `npm start` to enable a secure server.
2. In `firmware` folder you can see a modified makefile that enables `U2F` and sets the scramble key to `algo`
3. In `openLedger` function located in `LedgerUSB.js`, comment the `TransportWebAuthn` & `TransportU2F` `if` blocks to use WebUSB and see it working on Chrome.
4. Windows support sucks. Ledger guys says something but many people if complaining about the lack of support mainly after Microsoft released update 1903. They don't provide any drive.
5. Our goal is to try to support the most used browsers via U2F because, currently, WebUSB is supported only by Chrome.
6. With `U2F` I get a transport error code 2 (it is supposed to mean bad request) Based on https://github.com/LedgerHQ/ledger-app-eth seems there is some extra work to do inside the app code in order to properly handle `U2F` messages.

Kind regards,
Mauro.

**Comment by zeldovich** [comment]
Thanks.

I've pushed a commit that enables U2F transport support for the Algorand Ledger app.

Your demo app has a small bug in it that prevents it from working with U2F transport as-is; I had to make this change to get it to work:

```
--- a/src/LedgerUSB.js
+++ b/src/LedgerUSB.js
@@ -38,7 +38,7 @@ export default class LedgerUSB {
 
        async getAddress() {
                await openLedger(this);
-               const publicKey = await queueCommand(this, Buffer.from([ CLA, INS_GET_PUBLIC_KEY ]));
+               const publicKey = await queueCommand(this, Buffer.from([ CLA, INS_GET_PUBLIC_KEY, 0, 0, 0 ]));
                return algosdk_address.encode(publicKey);
        }
 }
```

**Comment by mxmauro** [comment]
Fascinating. Thanks for pointing it out.

**Comment by mxmauro** [comment]
Hi @zeldovich , tested the code on Windows 10 1809 and also works fine after installing a generic WinUsb driver for Nano S. On Windows 10 1903 something changed on the OS that Ledger guys should review.

Thanks and kind regards,
Mauro.
