### ISSUE TITLE
Ledger Algorand app only supports 1 account

### ISSUE THREAD

**Issue by pbennett** [algorand/ledger-app-algorand#22]
The Algorand Ledger 'App' appears to be locked into allowing only a single account.
Normally with things like ETH, you can add new accounts (via hierarchical derviation from master seed) over and over.  

KMD already supports this for 'local' Algorand accounts - single wallet, create new accounts based on that wallet seed using goal account new.

The ledger app should work the same way via the Algorand mobile app, as well as the goal CLI.

This should work for eg:
```
goal account new -w Ledger-Nano-X-0001-xxxxx
Error processing command: operation not supported by wallet
```

Requiring users to reset their Ledger, and/or using an alternative seed via a passphrase (again requiring effective reload) just to be able to use multiple Algorand accounts is unusual.  I haven't encountered another coin w/ Ledger support that works this way.

Is this going to be addressed?

**Comment by tsachiherman** [comment]
I have created two templates - one for bug reports, and one for feature requests. Could you please recreate this issue using the new issue template and close this one ?

**Comment by pbennett** [comment]
I just created this at https://github.com/algorand/go-algorand/issues/1930
Ledger live supports it so I know the capability is there in the app - it's thus just a goal deficiency at this point.
