### ISSUE TITLE
Ledger unable to sign 'online' transaction for participation key.

### ISSUE THREAD

**Issue by pbennett** [algorand/ledger-app-algorand#23]
I believe this has already been reported, but I wanted to create an issue to be sure.
I'm unable to use an account on the ledger and sign the 'goal account changeonlinestatus -w Ledger-XXX -a xxxxxx -o 1' transaction, with it producing an error regarding one of the fields.

**Comment by pbennett** [comment]
The error received is:
```
Couldn't sign tx: unknown field votefst (for multisig accounts, write tx to file and sign manually)
```

**Comment by zeldovich** [comment]
You're right -- we are missing support for the VoteFirstValid / VoteLastValid fields in the ledger app.  Those fields were introduced in the Algorand protocol after we added support for the original keyreg transactions to the Ledger app, and we never went back to fill them it, apparently..  Should be pretty easy to fix.

**Comment by tsachiherman** [comment]
I have created two templates - one for bug reports, and one for feature requests. Could you please recreate this issue using the new issue template and close this one ?

**Comment by pbennett** [comment]
I believe this issue has already been addressed.  I would have expected it to be closed with a link to the PR addressing the issue but I don't think the codebase has been updated in months either.  

I'll close this issue because it's already been fixed, but my suggestion is it would be more respectful of peoples time if the issues they created (and months with no response) should be handled as-is, not ask them to completely recreate the issues as the first response seen in 3 months.   I think the 4 issues that exist are pretty clear in their asks and a newly 'formatted' version of the ask isn't going to change much - particularly when the template references goal and node versions, none of which apply for the Ledger hardware wallet.  So the information asked in the template isn't even relevant.
