### ISSUE TITLE
Windows issue while signing

### ISSUE THREAD

**Issue by mxmauro** [algorand/ledger-app-algorand#28]
Hi! I'm recreating #27 with the new template.

Resume: With U2F, when sign is confirmed on device, first we get

![image](https://user-images.githubusercontent.com/1683070/92961694-0fe86d00-f446-11ea-96c3-fd77d11eb91f.png)

It happens on Windows on the latest releases but the problem does not happen to all people.

UPDATE:

Seems some sort of timing issue because if you retry several times, later or sooner it works.

We tried to switch to WebUSB and WebAuth. In the former, unless the user has the proper drivers, the browser does not recognizes the device. In the latter, seems to work a bit better than U2F but also fails.

Regards,
Mauro.

**Comment by rotemh** [comment]
Seems to be solved with the latest version. Please reopen if still persists.
