### ISSUE TITLE
1.0.2 in Ledger Live

### ISSUE THREAD

**Issue by mxmauro** [algorand/ledger-app-algorand#3]
Hi Nickolai,

Is it possible to upload v1.0.2 to Ledger Live? It has U2F support.

Thanks,
Mauro.

**Comment by zeldovich** [comment]
I can't do it from my end.  This requires Ledger folks to approve our PR (https://github.com/LedgerHQ/ledger-app-algorand/pull/1) which has been there for almost two months now.

**Comment by mxmauro** [comment]
I'll revive it. Thanks!!
