### ISSUE TITLE
Critical bug due to caching of ALGO public-key/address in Algorand ledger app

### ISSUE THREAD

**Issue by loupiote** [algorand/ledger-app-algorand#32]
Just making sure that you get aware of the critical bug reported here: 

https://www.reddit.com/r/ledgerwallet/comments/mb9brr/psa_do_not_use_algo_with_the_ledger_via_the_algo/

You should never cache the ALGO account address in the Algorand ledger app, because the ledger seed is not always the same:

A user can use a BIP39 passphrase and this will generate different seeds (with  the active/unlocked seed being derived from the currently used passphrase - or empty passphrase if none is used).

The bug is critical and can cause permanent loss of ALGO assets.

Note: this bug also affects https://algorandwallet.com/ , but I cannot find their Github to report it.

**Comment by zeldovich** [comment]
Thanks for the note.

The reddit description of the problem sounds a bit confusing.  As far as I understand things, there's nothing being cached in flash memory.  The private and public key gets cached in SRAM on app startup; restarting the app re-computes the keys.

It would be good to hear from the Ledger folks about what is the right way to address such issues.  The reason for the caching is that BIP39 derivation is rather slow on Ledger hardware, and simply removing caching makes the app more painful to use.  Perhaps there's some way for a Ledger app to determine if the underlying BIP39 seed has changed?  @TamtamHero ?

**Comment by Alex99y** [comment]
Hello @zeldovich ! I reproduced the bug with the next steps: 
* Create/Import Ledger account by 24 words seed, install Algorand Ledger App, and Open it.
* Go to MyAlgo and check the public address.
* Go to LEDGER settings and create a passphrase with a password.
* Open Ledger App and wait until autolock locks your device.
* Unlock your device with the new PIN associated with the passphrase you have been created.
* Go to MyAlgo and check the public address. It will show the ORIGINAL Account instead of the newly created one.
To solve this issue, just unplugged the Ledger Nano S or close and open Algorand App and it will show you the new account.

I used Ledger Nano S last version, Chrome 89 (WebUSB), and Ubuntu 18.

**Comment by pipaman** [comment]
It is not a critical issue and it is difficult to reproduce even trying.

**Comment by loupiote** [comment]
In my book, any bug that can cause loss of funds (in certain scenarios) is a critical bug.

And any bug that can cause a wallet (connected to a hardware device) to to generate an address unrelated to the seed currently unlocked in the hardware device, is a critical bug.

I took me 5 min to find this bug, and I was not even looking for it! And in the scenario I describe, it could have easily caused loss of funds.

I find it disturbing that Algorand dismisses this as a non-critical bug. Maybe you should be glad I found (and reported) the bug before someone lost large funds because of this issue.

Maybe what made it easier for me to find the bug is that I was using a Nano X (which I rarely turn off). Locking the Nano X does not erase the data cached by the Algorand app (I know since I locked and unlocked with a different PIN to change my seed).

Also, switching seeds by entering a temporary passphrase does not erase the data cached by the Algorand app either. And this can be done on the Nano S too.

Yes, turning the device off does erase it, but in the case of the Nano X, unplugging the device does not turn it off.

**Comment by loupiote** [comment]
@Alex99y

Note that changing the seed by entering a temporary passphrase (on both Nano S and Nano X) will cause the bug.

**Comment by loupiote** [comment]
@zeldovich

> It would be good to hear from the Ledger folks about what is the right way to address such issues. The reason for the caching is that BIP39 derivation is rather slow on Ledger hardware, and simply removing caching makes the app more painful to use. Perhaps there's some way for a Ledger app to determine if the underlying BIP39 seed has changed?

Well, it is trivial to determine if the BIP39 seed has changed: Just query any "address" (or public key) derived from that seed with a given path (e.g. m/0'/0' or any other path that you like, maybe just m/0' will work).  If, for the same derivation path, you get a different value, it means that the seed has changed!

**Comment by zeldovich** [comment]
> Well, it is trivial to determine if the BIP39 seed has changed: Just query any "address" (or public key) derived from that seed with a given path (e.g. m/0'/0' or any other path that you like, maybe just m/0' will work). If, for the same derivation path, you get a different value, it means that the seed has changed!

Indeed, that would work, though I was (implicitly) wondering if there's an efficient way to do this.  Querying some other path would not make sense in the grand scheme of things: at that point, we might as well suffer the cost of doing the BIP39 derivation for the intended path.  Since that cost is pretty significant, I'm hesitant to just outright change the code to do the BIP39 derivation on, say, every APDU.

**Comment by algorotem** [comment]
@loupiote FYI, Algorand doesn't build and maintain MyAlgoWallet but we do drive the ledger firmware and the Algorand Wallet App. 

I've tried to reproduce the bug with the official Algorand Wallet app without success. 
The wallet correctly shows the relevant address when I try to add a new account with the ledger, with and without a passphrase (I tried both temporarily and by attaching a pin to it). 
Can you please provide us with specific instructions for how to reproduce it in the Algorand Wallet app?

**Comment by loupiote** [comment]
@algorotem 

There are many way to reproduce the issue. Here is one I used:

Setup a Nano X with a passphrase, attached to PIN2. PIN1 is the regular pin that unlocks the non-passphrased seed. PIN2 unlocks the passphrased seed.

Pair the Nano X to your phone with bluetooth

Unlock the Nano X with PIN2, go in the Algorand app on the Ledger.

Start the Algorand wallet on the phone and obtain an Algo account address. Take note of the address (I did not save it in the wallet, and I went back to initializing of the Algorang wallet).

Lock the Nano X (ledger > Dashboard > Lock), the unlock the Nano X, this time with PIN1 (i.e. a different seed). Quit the dashboard, make sure you are still in the Algorand app on the nano X.

In the Algorand wallet on the phone , obtain an Algo account address.

EXPECTED: you should get an ALGO address derived from the currently active seed in your ledger.

OBSERVED: you get the same ALGO address as before, i.e. an address derived from the previously active seed (not the seed currently unlocked in your Ledger).

**Comment by loupiote** [comment]
Note that the bug in not in the Algorand wallet on the phone. The bug is in the Algorand app that runs on the ledger. The app on the ledger incorrectly caches seed-related data.  And this data is incorrect after the seed has changed, of course. So it can affect any wallet that connects to the ledger and use the Algorand app on the ledger.

**Comment by loupiote** [comment]
By the way, what is the derivation path for ALGO account #n derived from the seed?

This is important info that should be made public, in case there are issues recovering access to old accounts, in the future (I know several cryptos that changed their derivation paths, causing problems with legacy accounts (e.g. ETH, FLOW).

People from MyAlgo said: _Currently, MyAlgo does not ask for a specific derivation path, we just call the operation INS_GET_PUBLIC_KEY and Algorand App gives us the first account by default._

So what is the derivation path that is used in the Algorand app when a public key is queried?

**Comment by loupiote** [comment]
@zeldovich 

> at that point, we might as well suffer the cost of doing the BIP39 derivation for the intended path. Since that cost is pretty significant

Is the cost of doing one simple derivation (within the ledger) so significant? It is more than a few milliseconds?

I never got the impression that it was, compared to the "time" cost of slow USB communication between the host and the Ledger.

**Comment by loupiote** [comment]
@zeldovich 

> Since that cost is pretty significant, I'm hesitant to just outright change the code to do the BIP39 derivation on, say, every APDU.

I don't think you need to do the derivation for _each_ APDU, but you should do it when there is a request for a public key/address, and when a Tx must be signed.

**Comment by zeldovich** [comment]
> By the way, what is the derivation path for ALGO account #n derived from the seed?

https://github.com/algorand/ledger-app-algorand/blob/master/src/algo_keys.c#L9

> Is the cost of doing one simple derivation (within the ledger) so significant? It is more than a few milliseconds?

Yes, it is well over a second as far as I can recall.

**Comment by loupiote** [comment]
@zeldovich 

> Yes, it is well over a second as far as I can recall.

I frankly doubt it.  I will ask @btchip if path derivation can ever take that much time.

**Comment by loupiote** [comment]
Thanks! So Algorand derivation path is m/44'/283'/x'/0/0 for account #x

I think people should not need to go in the source code to get this info... It should be published somewhere, and it would be nice to have wallets or other recovery tools able to recover the keys from the BUP39 seed and the Algorand derivation path.

**Comment by algoidan** [comment]
fixed
