### ISSUE TITLE
Cannot sign axfer transactions

### ISSUE THREAD

**Issue by mxmauro** [algorand/ledger-app-algorand#5]
Hi,

When I try to sign an axfer (asset transfer) transaction I get, as a response the status OK, with 85 bytes. The first 64 with zero (I think the signature) followed by the text "unknown tx type axfer".

Is this ok? Because I was expecting an error code as the status.

Regards,
Mauro.

**Comment by zeldovich** [comment]
Regarding how errors are reported: if there's more bytes than just the signature, then this is an error and bytes following the signature blob are the error string.  The reason we don't report error strings with an error APDU code is that some ledger libraries (like the python one) ignore the payload for error responses, so the application client code can't get the error string.

I've also pushed a change to support the "axfer" and "afrz" txn types; see if that helps.

**Comment by mxmauro** [comment]
Excellent @zeldovich . Then I'll adjust the code to the behavior.

Hope the new code is on Ledger Live soon.
