### ISSUE TITLE
Yieldy ASA breaks Ledger Live on desktop

### ISSUE THREAD

**Issue by tvarsis** [algorand/ledger-app-algorand#52]
### Your environment
* Software version: 1.2.15 
* Operating System details: OpenSUSE Tumbleweed

### Steps to reproduce

1. Add you Algo account on Ledger
2. Open it up in AlgoWallet and import the account
3. Add Yieldy ASA in AlgoWallet
4. Send Yieldy and Algo tokens to Yieldy for staking and approve transactions from ledger
5. Now all dates of transaction seems to be 1970 in Ledger and that seems to break synchronization. 
6. Seems to work ok-ish on the mobile Ledger Live.
7. Might be fixed by fully supporting Yieldy ASA in the Algorand app or setting the correct date for transactions.

### Expected behaviour
Ledger Live should still sync and show correct amount of Algorand. Now the whole Algo account comes into a broken state on Ledger Live Desktop.

### Actual behaviour
Transaction timestamps are messed up, can't see correct amount or even the account of Algo if you remove and try to add it back again.

Here is a bug report on the Ledger Live app. Not sure which side needs to fix this issue, probably both:

[https://github.com/LedgerHQ/ledger-live-desktop/issues/4226](https://github.com/LedgerHQ/ledger-live-desktop/issues/4226)

**Comment by brettseven** [comment]
I opened an issue on the Ledger Live desktop github page, and saw that other people reported the same issue. Why is this still not fixed?

**Comment by libert-xyz** [comment]
> I opened an issue on the Ledger Live desktop github page, and saw that other people reported the same issue. Why is this still not fixed?

can you share the link of the issue?

**Comment by algoanne** [comment]
closing this old issue, but let me know if anything here is still relevant.
