### ISSUE TITLE
Unable to sign transactions using Ledger Nano X after firmware 2.0.0 update

### ISSUE THREAD

**Issue by r0qs** [algorand/ledger-app-algorand#53]
### Subject of the issue

Hi, I recently updated my ledger nano X to the firmware version 2.0.0 but this seems to break the ability to sign transactions using the algorand wallet. I can successfully connect to my ledger using the algorand wallet app and import the ledger accounts but when I attempt to send some transaction the app cannot connect with the ledger for some reason.

### Your environment

* Android 8.1.0
* Ledger firmware 2.0.0
* Algorand Ledger app 1.2.15
* Algorand Wallet 4.10.6

### Steps to reproduce

1. Ensure that the bluetooth is enabled and the ledger is unlocked
2. Connect your ledger device with your phone
3. Open Algorand Wallet app and the ledger app
4. Try to send some transaction

Optional: You can also try to import some account from the ledger, and you will see that this functionality works and the accounts from the ledger are listed. So the connection with the ledger can be established.

### Expected behaviour

The app should request the user to confirm and sign the transaction.

### Actual behaviour

The following error is reported:
```
Connection Error: Could not connect to the Ledger device.
Make sure the device is unlocked, nearby and has bluetooth enabled.
```

**Comment by r0qs** [comment]
I can confirm what @mitsinsar said. After remove the account from the algorand wallet and re-pairing the device and add the account again, I could successfully sign and send a transaction.

**Comment by rob-code** [comment]
The very comprehensive discussion on the algorand forum should be helpful and are on going

**Comment by mitsinsar** [comment]
> @r0qs @mitsinsar , were you using an IOS device or Android? I am having issues even after Bluetooth repair & App resync account. Using Galaxy S10+/Android 11

I am using Samsung Galaxy A52 Android 11. I had to clear my network preferences from settings before re-pairing Ledger.

**Comment by djarind2** [comment]
@mitsinsar - I tried everything here I believe.  Can you confirm?  I actually fully uninstalled the Algorand Wallet and re-installed it.  Then repaired ledger account successfully.  but still can't send a transaction.  Then removed account and repaired again successfully... Still no transaction ability.  I fully reset all pairings before doing this as well. So still at a loss... Thanks for any insight
