### ISSUE TITLE
Stuck in tx review menu

### ISSUE THREAD

**Issue by scnale** [algorand/ledger-app-algorand#55]
### Subject of the issue

Hi, I was trying to sign a transaction and stumbled across this issue. When the transaction review appeared in my Nano S, I was able to look at all fields but suddenly got stuck while the screen displayed:
```
Txn type
Payment
```

### Your environment

Ledger Nano S firmware version 2.0.0.
Algorand Ledger application version 1.2.15

I was using the MyAlgo Connect method in [the governance application](https://governance.algorand.foundation/governance-period-1) with a Firefox browser in Linux (Arch, btw :P). But I doubt it's relevant.

### Steps to reproduce

1. Request a transaction to be signed by the device.
2. Once the display shows: 
```
👁️ Review
Transaction
```
Press the right button to go forward in the transaction review menu.

3. Press the left button to go back in the transaction review menu.

### Expected behaviour

The display shows:
```
👁️ Review
Transaction
```
once again and allows you to navigate the rest of the menu.

### Actual behaviour

The display is stuck at
```
Txn type
Payment
```
and doesn't respond to either the left or right buttons being pressed.

My guess is that it could be stuck in a very large or infinite loop. I've been looking a bit at how the application works and what I found suspicious were the following lines:
https://github.com/algorand/ledger-app-algorand/blob/master/src/ui_txn2.c#L63
https://github.com/algorand/ledger-app-algorand/blob/master/src/ui_txn2.c#L66
In both of these, the `current_data_index` is checked against negative values. However, the `current_data_index` variable is declared as `uint8_t`. This means that expressions like `current_data_index >= 0` will always evaluate to `true`.

I didn't try to actually confirm my suspicion that this is the culprit however.

**Comment by dgarroDC** [comment]
I reproduced it using Chrome on Windows 10 (the rest of my environment is the same as yours)

**Comment by dgarroDC** [comment]
I tried again after updating the app to 1.2.16 and the issue wasn't reproduced, it seems it was fixed

**Comment by scnale** [comment]
I confirmed the same. I can no longer reproduce this bug in v1.2.16. I'm closing this.
