### ISSUE TITLE
Customization of the transaction confirmation

### ISSUE THREAD

**Issue by ma-spadafora** [algorand/ledger-app-algorand#61]
## Problem

When you request the signature, all the details of the transaction are shown on the device display.
Given the small size of the display, it may be necessary to scroll many pages before arriving at the confirmation.
For example 15 pages are needed for a simple ApplicationNoOpTxn.

## Solution

It would be nice if the application allowed -through appropriate input parameters- to sign without confirmation on the display or to customize the confirmation message.

**Comment by rotemh** [comment]
Hi ma-spadafora, 

Thanks for the suggestion. It's the classic tradeoff of usability - security and when it comes to signing transactions, we always choose security. The users need to know what they sign and therefore, any hiding of information is unfortunately not possible.
