### ISSUE TITLE
Unsupported lease field

### ISSUE THREAD

**Issue by M-Picco** [algorand/ledger-app-algorand#63]
## Problem

Algorand Ledger App does not currently support the [`lease` field](https://developer.algorand.org/docs/get-details/transactions/transactions/?query=lease&object_source=false#common-fields-header-and-type).

When trying to sign a transaction with a non-null `lease` field, the normal process of show and approval is not followed; instead, a base 64 encoded message `unknown field lx` is immediately returned.

## Solution

Include the `lease`/`lx` field in the decoding and signing process.

**Comment by ainhoa-a** [comment]
This can be closed as it has been implemented and it was part of the latest Ledger app release version 2.1.7
  https://github.com/algorand/ledger-app-algorand/pull/79
